site_name: QuatschAndSuch
repo_url: https://github.com/QuatschVirus/QuatschAndSuch#
repo_name: QuatschAndSuch

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.top

markdown_extensions:
  - toc:
      permalink: "#"

plugins:
  - search